version: 2

# The default job builds the code, Python bindings and tests with different
# compilers, and then run the corresponding tests. The compilers to used are
# indicated by the CC/CXX environment variables.
default_job: &default_job
  docker:
    - image: cosmoepfl/rascal-ci:1
  steps:
    - checkout
    - run:
        name: Install Python dependencies
        command: python3.6 -m pip install -r requirements.txt
    - run:
        name: Configure
        command: |
          mkdir build
          cd build
          cmake ${CMAKE_EXTRA} -DBUILD_BINDINGS=ON -DBUILD_TESTS=ON \
                -DBUILD_EXAMPLES=ON -DBUILD_PROFILES=ON \
                -DBUILD_BENCHMARKS=ON -DRUN_BENCHMARKS_FLAGS=--benchmark_min_time=0.0000001 \
                -DCPPLINT=CPPLINT-NOTFOUND \
                -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
    - run:
        name: Build
        command: cd build && make -j2
    - run:
        name: Run tests
        command: cd build && ctest --output-on-failure
    - run:
         name: Run benchmarks
         command: cd build && make benchmarks
jobs:
  gcc-5:
    environment:
      CC: gcc-5
      CXX: g++-5
    <<: *default_job
  gcc-9:
    environment:
      CC: gcc-9
      CXX: g++-9
    <<: *default_job
  gcc-9-debug:
    environment:
      CC: gcc-9
      CXX: g++-9
      CMAKE_EXTRA: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG=
    <<: *default_job
  clang-4:
    environment:
      CC: clang-4.0
      CXX: clang++-4.0
    <<: *default_job
  clang-9:
    environment:
      CC: clang-9
      CXX: clang++-9
    <<: *default_job
  clang-9-debug:
    environment:
      CC: clang-9
      CXX: clang++-9
      APT_EXTRA_INSTALL: apt install -y clang-9
      CMAKE_EXTRA: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG=
    <<: *default_job
  # Special job only building the documentation
  docs:
    docker:
    - image: cosmoepfl/rascal-ci:1
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: python3.6 -m pip install -r requirements.txt
      - run:
          name: Configure
          command: |
            mkdir build
            cd build
            cmake -DBUILD_DOC=ON -DBUILD_BINDINGS=ON ..
      - run:
          name: Build docs
          command: cd build && make doc
      - run:
          name: Deploy docs
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
                ./.circleci/deploy-docs.sh
                cd gh-pages
                git push -q https://${GH_TOKEN}@github.com/cosmo-epfl/librascal.git gh-pages
            fi

  # Special job only linting the code
  lint:
    docker:
    - image: cosmoepfl/rascal-ci:1
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: python3.6 -m pip install -r requirements.txt
      - run:
          name: Configure
          command: |
            mkdir build
            cd build
            cmake -DBUILD_BINDINGS=OFF ..
      - run:
          name: Lint the code
          command: cd build && make lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - docs
      - gcc-5
      - gcc-9
      - gcc-9-debug
      - clang-4
      - clang-9
      - clang-9-debug
