version: 2

# The default steps builds the code, Python bindings and tests with different
# compilers, and then run the corresponding tests. The compilers to used are
# indicated by the CC/CXX environment variables.
default_steps: &default_steps
  steps:
    - checkout
    - run:
        name: Install Python dependencies
        command: python3.6 -m pip install -r requirements.txt
    - run:
        name: Configure
        command: |
          mkdir build
          cd build
          cmake ${CMAKE_EXTRA} -DBUILD_BINDINGS=ON -DBUILD_TESTS=ON \
                -DCPPLINT=CPPLINT-NOTFOUND \
                -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
    - run:
        name: Build
        command: cd build && make -j2
    - run:
        name: Run tests
        command: cd build && ctest --output-on-failure

jobs:
  release:
    parallelism: 4
    docker:
      - image: cosmoepfl/rascal-ci-gcc-5:2
      - image: cosmoepfl/rascal-ci-gcc-9:2
      - image: cosmoepfl/rascal-ci-clang-4:2
      - image: cosmoepfl/rascal-ci-clang-9:2
    <<: *default_steps
  debug:
    parallelism: 2
    docker:
      - image: cosmoepfl/rascal-ci-gcc-9:2
      - image: cosmoepfl/rascal-ci-clang-9:2
    environment:
      CMAKE_EXTRA: -DCMAKE_BUILD_TYPE=Debug
    <<: *default_steps
  # Special job only building the documentation
  docs:
    docker:
    - image: cosmoepfl/rascal-ci-clang-9:2
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: python3.6 -m pip install -r requirements.txt
      - run:
          name: Configure
          command: |
            mkdir build
            cd build
            cmake -DBUILD_DOC=ON -DBUILD_BINDINGS=ON ..
      - run:
          name: Build docs
          command: cd build && make doc
      - run:
          name: Deploy docs
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
                ./.circleci/deploy-docs.sh
                cd gh-pages
                git push -q https://${GH_TOKEN}@github.com/cosmo-epfl/librascal.git gh-pages
            fi

  # Special job only linting the code
  lint:
    docker:
    - image: cosmoepfl/rascal-ci-clang-9:2
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: python3.6 -m pip install -r requirements.txt
      - run:
          name: Configure
          command: |
            mkdir build
            cd build
            cmake -DBUILD_BINDINGS=OFF ..
      - run:
          name: Lint the code
          command: cd build && make lint

workflows:
  version: 2
  all:
    jobs:
      - lint
      - docs
      - debug
      - release
