version: 2

# The default job builds the code, Python bindings and tests with different
# compilers, and then run the corresponding tests. The compilers to used are
# indicated by the CC/CXX environment variables.
default_job: &default_job
  docker:
    - image: ubuntu:18.04
  steps:
    - run:
        name: Install dependencies
        command: |
          apt update -y
          apt install -y git cmake python3.6 python3-pip libboost-test-dev
          ${APT_EXTRA_INSTALL}
    - checkout
    - run:
        name: Install Python dependencies
        command: python3.6 -m pip install -r requirements.txt
    - run:
        name: Configure
        command: |
          mkdir build
          cd build
          cmake ${CMAKE_EXTRA} -DBUILD_BINDINGS=ON -DBUILD_TESTS=ON \
                -DCPPLINT=CPPLINT-NOTFOUND \
                -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
    - run:
        name: Build
        command: cd build && make -j2
    - run:
        name: Run tests
        command: cd build && ctest --output-on-failure

jobs:
  gcc-5:
    environment:
      CC: gcc-5
      CXX: g++-5
      APT_EXTRA_INSTALL: apt install -y gcc-5 g++-5
    <<: *default_job
  gcc-6:
    environment:
      CC: gcc-6
      CXX: g++-6
      APT_EXTRA_INSTALL: apt install -y gcc-6 g++-6
    <<: *default_job
  gcc-7:
    environment:
      CC: gcc-7
      CXX: g++-7
      # Not actually needed since gcc-7 is the default on Ubuntu 18.04
      # but this protect use against unwanted changes
      APT_EXTRA_INSTALL: apt install -y gcc-7 g++-7
    <<: *default_job
  gcc-7-debug:
    environment:
      CC: gcc-7
      CXX: g++-7
      # Not actually needed since gcc-7 is the default on Ubuntu 18.04
      # but this protect use against unwanted changes
      APT_EXTRA_INSTALL: apt install -y gcc-7 g++-7
      CMAKE_EXTRA: -DCMAKE_BUILD_TYPE=Debug
    <<: *default_job
  clang-4:
    environment:
      CC: clang-4.0
      CXX: clang++-4.0
      APT_EXTRA_INSTALL: apt install -y clang-4.0
    <<: *default_job
  clang-5:
    environment:
      CC: clang-5.0
      CXX: clang++-5.0
      APT_EXTRA_INSTALL: apt install -y clang-5.0
    <<: *default_job
  clang-6:
    environment:
      CC: clang-6.0
      CXX: clang++-6.0
      APT_EXTRA_INSTALL: apt install -y clang-6.0
    <<: *default_job
  clang-7:
    environment:
      CC: clang-7
      CXX: clang++-7
      APT_EXTRA_INSTALL: apt install -y clang-7
    <<: *default_job
  clang-7-debug:
    environment:
      CC: clang-7
      CXX: clang++-7
      APT_EXTRA_INSTALL: apt install -y clang-7
      CMAKE_EXTRA: -DCMAKE_BUILD_TYPE=Debug
    <<: *default_job
  # Special job only building the documentation
  docs:
    docker:
    - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update -y
            apt install -y git cmake python3.6 python3-pip
            apt install -y doxygen pandoc
      - checkout
      - run:
          name: Install Python dependencies
          command: python3.6 -m pip install -r requirements.txt
      - run:
          name: Configure
          command: |
            mkdir build
            cd build
            cmake -DENABLE_DOC=ON -DBUILD_BINDINGS=OFF ..
      - run:
          name: Build docs
          command: cd build && make doc
  # Special job only linting the code
  lint:
    docker:
    - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update -y
            apt install -y git cmake python3.6 python3-pip
      - checkout
      - run:
          name: Install Python dependencies
          command: python3.6 -m pip install -r requirements.txt
      - run:
          name: Configure
          command: |
            mkdir build
            cd build
            cmake -DBUILD_BINDINGS=OFF ..
      - run:
          name: Lint the code
          command: cd build && make lint

workflows:
  version: 2
  run_all:
    jobs:
      - lint
      - docs
      - gcc-5
      - gcc-6
      - gcc-7
      - gcc-7-debug
      - clang-4
      - clang-5
      - clang-6
      - clang-7
      - clang-7-debug
