version: 2
jobs:
        build: 
                docker:
                        - image: ubuntu:18.04
                          environment:
                                  PIPENV_VENV_IN_PROJECT: true
                steps:
                        - checkout
                        - run: 
                                name: setting up apt-get properly
                                command: |
                                        apt-get update -y
                        - run:
                                name: Installing dependencies
                                command: |
                                        apt-get install -y cmake
                                        apt-get install -y python3-pip
                                        apt-get install -y python3.6
                                        apt-get install -y git
                                        apt-get install -y libboost-test-dev
                                        apt-get install -y doxygen
                                        apt-get install -y software-properties-common
                                        apt-get update -y
                                        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
                                        add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main'
                                        #add-apt-repository 'deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main' 
                                        apt-get install -y libllvm-7-ocaml-dev libllvm7 llvm-7 llvm-7-dev llvm-7-doc llvm-7-examples llvm-7-runtime
                                        apt-get install -y clang-7 clang-tools-7 clang-7-doc libclang-common-7-dev libclang-7-dev libclang1-7 clang-format-7 python-clang-7
                                        apt-get install -y libc++-7-dev libc++abi-7-dev
                        - run: 
                                name: installing python packages
                                command: |
                                        python3.6 -m pip install --upgrade pip
                                        python3.6 -m pip install numpy scipy sphinx breathe sphinx_rtd_theme cpplint
                        - run: 
                                command: |
                                        rm -rf build 
                                        mkdir build 
                                        cd build 
                                        cmake -DENABLE_DOC=ON -DBUILD_TESTS=ON -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang-7 ..
                        - run: pwd
                        - run:
                                command: | 
                                        cd build 
                                        make lint
                        - run: 
                                command: |
                                        cd build 
                                        make 
                        - run: 
                                command: |
                                        cd build 
                                        ctest -V
                        - run: 
                                command: |
                                        cd build 
                                        make dev_doc
                        
